Posible solucion

diff --git a/.github/workflows/abstraccion.scala.yaml b/.github/workflows/abstraccion.scala.yaml
--- a/.github/workflows/abstraccion.scala.yaml
+++ b/.github/workflows/abstraccion.scala.yaml
@@ -1,5 +1,3 @@
-# Tu archivo de flujo de trabajo de GitHub Actions
-
 name: Scala CI
 
 on:
@@ -33,13 +31,14 @@ jobs:
       run: |
         cd ./temas/abstraccion/scala/proyecto
         
-        # Ejecuta `sbt test` directamente sin entrar en la interfaz interactiva
-        sbt test
+        # Ejecuta `sbt test` y guarda la salida en la variable `test_output`
+        test_output=$(sbt test)
+        echo "$test_output" # Esta línea es opcional y solo para depurar
         
         # Verifica si hubo errores en la salida de sbt test
-        if echo "$test_output" | grep -q 'TESTS FAILED\|TEST FAILED'; then
+        if echo "$test_output" | grep -q 'FAILED'; then
           echo "Tests failed"
-          # Agrega aquí el código para crear el issue en GitHub
+          exit 1  # Cambia el estado a fallido para que GitHub Actions lo refleje
         else
-          echo $test_output
+          echo "All tests passed"
         fi
